version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:r0O7@mongo:27017/mibd?authSource=admin
    networks:
      - app-net

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r0O7
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

volumes:
  mongo-data:


networks:
  app-net:
    driver: bridge
